### PR TITLE
Update Utilities.cs

### PR DESCRIPTION
**Pull request by RyanMilligan**
This fixes a compile error that occasionally pops up and causes my Unity projects to stop building.

### CODE REVIEW

**Comment by RyanMilligan** [comment]
Fixes #151.

**Review by ryantrem — APPROVED** [review]
Thanks for this contribution!

**Review by jwittner — APPROVED** [review]

**Comment by sgh-msg** [comment]
Can we expect a new NPM package with this fix anytime soon?

**Comment by ryantrem** [comment]
I pinged @hendryems about this today but he is out on vacation. Hopefully next week we can do it!

**Comment by hendryems** [comment]
I have regenerated a new Nuget package containing this change `0.9.2-223520`

**Pull request merged**
